name: Testing

on:
  push:
    branches: 
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Build step
      - name: Build Project
        id: build
        run: |
          echo "Building the project"
          # Simulating failure
          exit 1
      - name: Set Build Status
        id: build_status
        if: success()
        run: echo "build_status=success" >> $GITHUB_ENV
      - name: Set Build Status Failure
        if: failure()
        run: echo "build_status=failure" >> $GITHUB_ENV

      # Helm installation step
      - name: Install Helm
        id: helm
        run: |
          helm version
      - name: Set Helm Status
        id: helm_status
        if: success()
        run: echo "helm_status=success" >> $GITHUB_ENV
      - name: Set Helm Status Failure
        if: failure()
        run: echo "helm_status=failure" >> $GITHUB_ENV

  notify:
    needs: build
    runs-on: ubuntu-latest
    if: always()  # Ensure the notification runs regardless of success or failure
    steps:
      - name: Notify Slack on Failure
        if: ${{ env.build_status == 'failure' || env.helm_status == 'failure' }}
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: 'C07KP9NV5N3'  # Replace with your Slack channel ID
          slack-message: |
            Workflow *${{ github.workflow }}* triggered by *${{ github.actor }}* has finished with a failure.
            Status: `${{ job.status }}`
            Job: Build and Helm Installation
            URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            Build Step Status:
            - Build: `${{ env.build_status }}`
            - Helm: `${{ env.helm_status }}`
            @channel
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Notify Slack on Success
        if: ${{ env.build_status == 'success' && env.helm_status == 'success' }}
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: 'C07KP9NV5N3'  # Replace with your Slack channel ID
          slack-message: |
            Workflow *${{ github.workflow }}* triggered by *${{ github.actor }}* has finished successfully.
            Status: `${{ job.status }}`
            Job: Build and Helm Installation
            URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            Build Step Status:
            - Build: `${{ env.build_status }}`
            - Helm: `${{ env.helm_status }}`
            @channel
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
