name: Test

on:
  push:
    branches: 
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Add your build steps here
      - name: Build Project
        run: echo "Building the project"

  notify:
    runs-on: ubuntu-latest
    if: always()  # This ensures the notification runs regardless of previous job status
    steps:
      - name: Notify Slack
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "Workflow *${{ github.workflow }}* triggered by *${{ github.actor }}* has finished. Status: `${{ job.status }}`. Job: `${{ job.name }}`. URL: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
