name: Test

on:
  push:
    branches: 
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Project
        id: build  # Set ID so we can reference it later
        run: |
          echo "Building the project"
        continue-on-error: true  # Continue even if build fails
        env:
          BUILD_STATUS: ${{ steps.build.outcome }}

      - name: Check Build Status
        if: failure()
        run: echo "Build failed" && echo "BUILD_STATUS=failure" >> $GITHUB_ENV

      - name: Install Helm
        id: helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 
          chmod 700 get_helm.sh
          ./get_helm.sh
          helm version
        continue-on-error: true  # Continue even if helm installation fails

      - name: Check Helm Status
        if: failure()
        run: echo "Helm installation failed" && echo "HELM_STATUS=failure" >> $GITHUB_ENV

      - name: Set Helm Status to Success if No Error
        if: success()
        run: echo "HELM_STATUS=success" >> $GITHUB_ENV

  notify:
    needs: build
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: 'C07KP9NV5N3'  # Replace with your Slack channel ID
          slack-message: |
            Workflow *${{ github.workflow }}* triggered by *${{ github.actor }}* has finished.
            Status: `${{ job.status }}`
            Job: Build and Helm Installation
            URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            Build Step Status:
            - Build: `${{ env.BUILD_STATUS }}`
            - Helm: `${{ env.HELM_STATUS }}`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
