name: successnotification

on:
  push:
    branches: 
      - "development"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Build step
      - name: Build Project
        id: build
        run: |
          echo "Building the project"
          # Simulating success here (remove 'exit 1' to allow success)  
          echo "Build successful"
          
      # Helm installation step
      - name: Install Helm
        id: helm
        run: |
          helm version

  notify:
    needs: build
    runs-on: ubuntu-latest
    if: success()  # Send notification only if all the above steps succeed
    steps:
      - name: Notify Slack on Success
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: 'C07KP9NV5N3'  # Replace with your Slack channel ID
          slack-message: |
            🎉 *Success Notification* 🎉
            
            Hi *${{ github.actor }}*, your deployment has been successful! 🚀
            
            *Repository:* ${{ github.repository }}
            *Branch:* ${{ github.ref }}
            *Triggered by:* ${{ github.actor }}
            *Workflow:* ${{ github.workflow }}
            
            You can check the details of your workflow run here:
            <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow Run>
            
            _Keep up the great work!_
          SLACK_BOT_TOKEN: 'xoxb-6094612483233-7669323618503-ZiC8JxbsMvpcuA2xWlbk4I17'  # Hardcoded Slack bot token
